//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JProject.Mvc.TableSvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TableSvc.IListSvc")]
    public interface IListSvc {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListSvc/TestSvc", ReplyAction="http://tempuri.org/IListSvc/TestSvcResponse")]
        string TestSvc();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListSvc/TestSvc", ReplyAction="http://tempuri.org/IListSvc/TestSvcResponse")]
        System.Threading.Tasks.Task<string> TestSvcAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListSvc/TestHasParametersMethod", ReplyAction="http://tempuri.org/IListSvc/TestHasParametersMethodResponse")]
        string TestHasParametersMethod(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListSvc/TestHasParametersMethod", ReplyAction="http://tempuri.org/IListSvc/TestHasParametersMethodResponse")]
        System.Threading.Tasks.Task<string> TestHasParametersMethodAsync(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListSvc/getJsonMsg2", ReplyAction="http://tempuri.org/IListSvc/getJsonMsg2Response")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(JProject.ServicesTest.Utilities.NavigationEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(JProject.ServicesTest.Utilities.NavigationEntity[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(JProject.ServicesTest.Entities.TicketEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(JProject.ServicesTest.Entities.TicketEntity[]))]
        JProject.ServicesTest.Utilities.JsonResult getJsonMsg2();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListSvc/getJsonMsg2", ReplyAction="http://tempuri.org/IListSvc/getJsonMsg2Response")]
        System.Threading.Tasks.Task<JProject.ServicesTest.Utilities.JsonResult> getJsonMsg2Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListSvc/getJsonMsg", ReplyAction="http://tempuri.org/IListSvc/getJsonMsgResponse")]
        JProject.ServicesTest.Utilities.NavigationEntity[] getJsonMsg();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListSvc/getJsonMsg", ReplyAction="http://tempuri.org/IListSvc/getJsonMsgResponse")]
        System.Threading.Tasks.Task<JProject.ServicesTest.Utilities.NavigationEntity[]> getJsonMsgAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListSvc/GetTicket", ReplyAction="http://tempuri.org/IListSvc/GetTicketResponse")]
        JProject.ServicesTest.Entities.TicketEntity[] GetTicket();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListSvc/GetTicket", ReplyAction="http://tempuri.org/IListSvc/GetTicketResponse")]
        System.Threading.Tasks.Task<JProject.ServicesTest.Entities.TicketEntity[]> GetTicketAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IListSvcChannel : JProject.Mvc.TableSvc.IListSvc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListSvcClient : System.ServiceModel.ClientBase<JProject.Mvc.TableSvc.IListSvc>, JProject.Mvc.TableSvc.IListSvc {
        
        public ListSvcClient() {
        }
        
        public ListSvcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ListSvcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ListSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ListSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string TestSvc() {
            return base.Channel.TestSvc();
        }
        
        public System.Threading.Tasks.Task<string> TestSvcAsync() {
            return base.Channel.TestSvcAsync();
        }
        
        public string TestHasParametersMethod(string str) {
            return base.Channel.TestHasParametersMethod(str);
        }
        
        public System.Threading.Tasks.Task<string> TestHasParametersMethodAsync(string str) {
            return base.Channel.TestHasParametersMethodAsync(str);
        }
        
        public JProject.ServicesTest.Utilities.JsonResult getJsonMsg2() {
            return base.Channel.getJsonMsg2();
        }
        
        public System.Threading.Tasks.Task<JProject.ServicesTest.Utilities.JsonResult> getJsonMsg2Async() {
            return base.Channel.getJsonMsg2Async();
        }
        
        public JProject.ServicesTest.Utilities.NavigationEntity[] getJsonMsg() {
            return base.Channel.getJsonMsg();
        }
        
        public System.Threading.Tasks.Task<JProject.ServicesTest.Utilities.NavigationEntity[]> getJsonMsgAsync() {
            return base.Channel.getJsonMsgAsync();
        }
        
        public JProject.ServicesTest.Entities.TicketEntity[] GetTicket() {
            return base.Channel.GetTicket();
        }
        
        public System.Threading.Tasks.Task<JProject.ServicesTest.Entities.TicketEntity[]> GetTicketAsync() {
            return base.Channel.GetTicketAsync();
        }
    }
}
